blank_issues_enabled: true
contact_links:
  - name: GitHub Community Support
    url: https://github.community/
    about: Ask and answer questions about GitHub.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Report security vulnerabilities related to GitHub.
