name: ❓ Question
description: Leave your questions about various things

labels: ["question"]
title: "question: "
#assignees: ["hoang-himself"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add a clear and detailed description of the question.
      placeholder: Attach images/videos if possible. These can be helpful in figuring out what the question is about.
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.
